version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
workflows:
    tests:
      jobs:
        - unit-tests