version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6
jobs:
  coveralls:
    docker:
      - image: 'circleci/node:12.18.0'
    steps:
      - checkout
      - run:
          name: Install and Make
          command: yarn && make test-coverage
      - coveralls/upload:
          parallel: true
  unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
workflows:
    tests:
      jobs:
        - unit-tests
        - coveralls